apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: my-ns
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: pod-nginx
  namespace: my-ns
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
