apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-dep
  name: nginx-dep2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-dep
status:
  loadBalancer: {}
