apiVersion: v1
kind: Pod
metadata:
  name: shared-volume
spec:
  containers:
  - name: nginx-web
    image: nginx
    volumeMounts: 
    - name: nginx-rootdir
      mountPath: /usr/share/nginx/html
  - name: change-rootdir
    image: busybox
    command: ['sh', '-c', 'for i in $(seq 100); do echo index-$i > /usr/share/nginx/html/index.html; sleep 2 ;done']
    volumeMounts: 
    - name: nginx-rootdir
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-rootdir
    emptyDir: {}
