apiVersion: v1
kind: Pod
metadata:
  name: host-volume 
spec:
  containers:
  - name: nginx-web
    image: nginx
    volumeMounts: 
    - name: nginx-rootdir
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-rootdir
    hostPath: 
     path: /data/nginx-rootdir
